#!/bin/sh
# run commit lint to check the commit message against our conventions
./common/autoinstallers/rush-commitlint/node_modules/.bin/commitlint \
  --config ./common/autoinstallers/rush-commitlint/commitlint.config.js --edit $1
