# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: v-next app CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 12

    strategy:
      matrix:
        node-version: [20.14.0]
    steps:
      - uses: actions/checkout@v4
      - run: git pull

      - run: rush install
      - run: rush build
        # continue-on-error: true

      - name: restart pm2
        if: always()
        run: pm2 restart v-next
      - name: Nofity to ntfy
        if: always()
        run: curl -d "🚀 v-next project restart success!!!" ntfy.sh/aaron-conlon
