# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: v-next app CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.14.0]
    steps:
      - uses: actions/checkout@v4
      - run: rush install
      - run: rush build

      - name: restart pm2
        run: cd /home/qyy/actions-runner/_work/delete-github-repos-in-batches/delete-github-repos-in-batches
      - run: pm2 restart v-next
